language: cpp
compiler:
- clang
- gcc

script:
- g++ -v
- ./scripts/build_and_test.sh

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
    packages:
        - gcc-5
        - g++-5
        - clang-3.6
