language: cpp
sudo: required
dist: trusty

compiler:
- gcc

before_install:
- if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- sudo apt-get update -qq

install:
- ./scripts/boost.sh
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script: 
- $CXX --version
- ./scripts/build_and_test.sh
