language: cpp
sudo: false
compiler:
- g++

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
#- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
#    CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
#    mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
#    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
#  else
#    brew install cmake
#  fi

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest
        - kalakris-cmake
        packages:
        - libboost1.55-all-dev
        - g++-5
        - cmake

script: ./build_and_test.sh
