language: cpp
compiler:
- clang
- gcc

script:
- g++ -v
- ./scripts/build_and_test.sh

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.9
        - g++-4.9
