language: cpp
sudo: false
compiler:
- g++

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest
        packages:
        - libboost1.55-all-dev
        - g++-4.8
        - cmake

script: ./build_and_test.sh
