language:
- cpp

compiler:
- clang 

sudo: true
os: osx

before_install:
- brew update
- brew reinstall boost --c++11
- export CPLUS_INCLUDE_PATH="/usr/local/include:${CPLUS_INCLUDE_PATH}"

script:
- ./scripts/build_and_test.sh
